name: current

on:
  workflow_dispatch:

jobs:
  primary:
    name: current
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: composer install

      - name: Generate key
        run: php artisan key:generate

      - uses: actions/cache/restore@v3
        id: cache
        with:
          key: ${{ runner.os }}-json-dir-{{ hashFiles('storage/app/foo') }}
          path: storage/app/foo
          restore-key: |
            ${{ runner.os }}-json-dir-

      - name: Run artisan command
        run: php artisan json:store now

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-json-dir-{{ hashFiles('storage/app/foo') }}
          path: storage/app/foo
